### ISSUE TITLE
Stop working at changeset 4ed7b37

### ISSUE THREAD

**Issue by zdm** [mhinz/vim-signify#163]
Hi.

Environment: 
```
gvim-x64-7.4.729
windows-8.1-x64
hg-3.4
```

Signs not displayed if I use vim-signify revision 4ed7b37 and later.

If I update working copy to previous revision - all works.

**Comment by zdm** [comment]
My signify related config settings:
```
let g:signify_vcs_list = [ 'hg', 'git' ]
```

**Comment by zdm** [comment]
Seems, that default hg diff command
```
hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 -- %f
```
not executed at all when I save buffer.

**Comment by mhinz** [comment]
Could you please paste the output of `:SignifyDebugUnknown`?

**Comment by zdm** [comment]
This is mercurial repo. Here is the output:
```
hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 -- "d:projectspcoreibPAnyEventA.PM"
=============================================================================================================
projectspcoreibPAnyEventA.PM: The system cannot find the file specified

git diff --no-color --no-ext-diff -U0 -- "UA.pm"
================================================
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
```

**Comment by mhinz** [comment]
Okay, and what's the output of `:echo expand('%:p')` in the same buffer? Apparently the call to `substitute()` does something weird.

(I pushed some commits in the meanwhile, although I think they are not related to this problem.)

**Comment by zdm** [comment]
Output
```
d:\projects\pcore\lib\P\AnyEvent\UA.pm
```

Yes, slashes are removed from path.

**Comment by mhinz** [comment]
Try changing this line: https://github.com/mhinz/vim-signify/blob/master/autoload/sy/repo.vim#L138
to `let cmd = substitute(a:cmd, '%f', fnameescape(a:path),     '')`.

Does this work?

**Comment by zdm** [comment]
I have updated signify to the latest commits.
Still not works, path still without slashes.

**Comment by mhinz** [comment]
Okay, I can reproduce this problem in my Win VM. It's really just the eternal problem of escaping paths between Windows and non-Windows systems. I'll look into it.

**Comment by mhinz** [comment]
Please use `git pull && git checkout win-escape` and see if it's working for you.

**Comment by zdm** [comment]
?

Where I should check this?

Git and mercurial works in command line with any path, that contains any
slash, "/" or "\".

**Comment by mhinz** [comment]
In your shell, in the plugin's directory. Currently you're using the `master` branch, but I pushed a potential fix to the `win-escape` branch. The command above switches to that branch.

The problem is that Vim's functions do different stuff depending on the underlying operating system. Specifically Vim's `substitute()` function is the problem. In the `win-escape` branch I replaced that function by `split()`, hoping that it yields better results.

**Comment by zdm** [comment]
substitute() is just replace substring occurrences, no matter under what
platform.

Maybe this would be helpful:

```
function! substitute_path_separator(path)
  return (s:is_windows && a:path =~ '\\') ?
        \ tr(a:path, '\', '/') : a:path
endfunction
```

**Comment by mhinz** [comment]
Long story short: it's not that easy. Doubling `\` would work in this particular case, but it would still break under different circumstances. Just as replacing all `\` by `/` would work, but this would of course also break in other cases.

A nice writeup about the problem: https://github.com/airblade/vim-system-escape

Anyway, the thing I mentioned above should work around that whole problem.

**Comment by mhinz** [comment]
Thanks for reporting!
