### ISSUE TITLE
No signification after ":w" in git subrepo of hg repository

### ISSUE THREAD

**Issue by Krakonos** [mhinz/vim-signify#235]
Hi!

I'm having trouble with signification in my setup, where we have a git subrepo inside a hg repository. Editing file in the git subrepo, I see signification as expected. However, after issuing ":w", I do not. Anything I do after that doesn't seem to matter, only restarting vim works fine. Issuing SingifyDebug shows the correct diff for git, then empty (also correct) diff from hg (hg diff returns 0)

Here are steps to reproduce:

```
krakonos@gazelle /tmp $ mkdir x
krakonos@gazelle /tmp $ cd x
krakonos@gazelle /tmp/x $ hg init
krakonos@gazelle /tmp/x $ mkdir y
krakonos@gazelle /tmp/x $ cd y
krakonos@gazelle /tmp/x/y $ git init
Initialized empty Git repository in /tmp/x/y/.git/
krakonos@gazelle /tmp/x/y $ vim f
krakonos@gazelle /tmp/x/y $ git add f
krakonos@gazelle /tmp/x/y $ git commit
[master (root-commit) 092d2ed] Hello.
 1 file changed, 2 insertions(+)
 create mode 100644 f
krakonos@gazelle /tmp/x/y $ vim f
```

Now changing something in f and saving does not signify at all, reopening the file shows the difference, but saving breaks it again.

Removing /tmp/x/.hg causes the problem to disappear.

I'm using latest vim-signify from master branch and Neovim v0.2.0-590-geaf9caaf4 on Arch Linux. However, I suspect it is a problem in vim-signify and interaction between git and mercurial.

I hope you will be able to reproduce and fix it, as I've grown very attached to this plugin!

**Comment by mhinz** [comment]
Thanks for the report, I can reproduce it just fine.

I'm looking into it.

**Comment by mhinz** [comment]
**Here's what happens:**

We use the exit code and returned diff of `git diff` and `hg diff` to determine the VCS for each file.
In this case, _both_, git and hg, return valid diffs (the hg diff being empty).

When Vim starts, the VCS is still unknown. Then it asynchronously runs all the VCS tools from `g:signify_vcs_list`. In your case that's at least `git` and `hg`.

It happens that git runs first: it finds a valid git diff, sets the signs accordingly, sets the VCS to git. But then hg runs and returns a valid, empty diff as well. Thus it doesn't bother setting signs and most importantly sets the VCS to hg.

When you `:w`, Sy tries to update the signs by running the currently set VCS, which is hg which will return an empty diff again and the current signs, previously set by git, will disappear.

---

So, yes, nested repos of different types are currently a problem. They're prone to race conditions. 

Maybe we should change Sy to allow multiple active VCS if the initial detection phase returns multiple valid diffs. Then multiple VCS tools would run, `hg diff` and `git diff` in this case, on each sign update (e.g. `:w`), which obviously produces some overhead but it shouldn't matter too much since they run asynchronously and it's also a rather rare case.

That's the only reliable way I see to solve this problem. We will assume that multiple VCS can return a valid diff, but only of them will be non-empty.

If the same file is checked in into multiple VCS, someone is doing something very wrong anyway. :-P

@jamessan Does this sound sane?

**Comment by jamessan** [comment]
Yeah, that sounds like the only sane thing to do.

**Comment by mhinz** [comment]
@Krakonos It would be great if you could test the above PR.

**Comment by Krakonos** [comment]
Thanks for the quick update! 

It's better: after :w, the signification seems to be correct, however there is no signification right after opening a file. Everything works fine after first :w, so the situation seems reversed. I am able to reproduce it on the example given above.

I will be using it for today and report back if I find any other problem.

**Comment by mhinz** [comment]
> Everything works fine after first :w, so the situation seems reversed.

Even with the example you gave above? Because that's the one I used for testing.

Please do the following steps and paste the output of the last step:

```vim
$ vim -V1 file
" use <esc> to discard the verbose output
:w
" use <esc> again
:tabedit +put=execute('messages')
" yank buffer content to clipboard (requires +clipboard in :version)
:%y +
```

Then paste it in here.

**Comment by Krakonos** [comment]
Yes, even in the example given above. Here is the output, hope it helps.

```
could not source "$VIM/sysinit.vim"
not found in 'runtimepath': "ftdetect/*.vim"
not found in 'runtimepath': "spell/cs.vim"
not found in 'runtimepath': "ftdetect/*.vim"
not found in 'runtimepath': "autoload/operator/user.vim"
not found in 'runtimepath': "autoload/operator/user.vim"
not found in 'runtimepath': "autoload/fzf.vim"
not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/*"
Reading ShaDa file "/home/krakonos/.local/share/nvim/shada/main.shada" info marks oldfiles
"file" 2L, 27C
Reading ShaDa file "/home/krakonos/.local/share/nvim/shada/main.shada" marks
Reading undo file: /home/krakonos/.vim/undo/%home%krakonos%tmp%signify-bug-235%x%y%file
[sy] Register new file.
[sy:git] get_diff_start()
[sy:git] CMD: ['sh', '-c', 'git diff --no-color --no-ext-diff -U0 -- ''file'''] | CWD: /home/krakonos/tmp/signify-bug-235/x/y
[sy:hg] get_diff_start()
[sy:hg] CMD: ['sh', '-c', 'hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 -- ''/home/krakonos/tmp/signify-bug-235/x/y/file'''] | CWD: /home/krakonos/tmp/signify-bug-235/x/y
[sy:git] job_exit()
[sy:git] get_diff_git()
[sy:git] get_diff_end()
[sy:git] set_signs()
[sy:git] Signs updated.
[sy:hg] job_exit()
[sy:hg] get_diff_hg()
[sy:hg] get_diff_end()
[sy:hg] set_signs()
[sy:hg] No changes found.
vim-misc 1.17.6: Checking handler xolox#session#auto_save_periodic with interval 60 and last run 0 ..
vim-misc 1.17.6: Running handler xolox#session#auto_save_periodic ..
"file" 2L, 27C written
Writing undo file: /home/krakonos/.vim/undo/%home%krakonos%tmp%signify-bug-235%x%y%file
[sy:git] Updating signs.
[sy:git] get_diff_start()
[sy:git] CMD: ['sh', '-c', 'git diff --no-color --no-ext-diff -U0 -- ''file'''] | CWD: /home/krakonos/tmp/signify-bug-235/x/y
[sy:hg] Updating signs.
[sy:hg] get_diff_start()
[sy:hg] CMD: ['sh', '-c', 'hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 -- ''/home/krakonos/tmp/signify-bug-235/x/y/file'''] | CWD: /home/krakonos/tmp/signify-bug-235/x/y
[sy:git] job_exit()
[sy:git] get_diff_git()
[sy:git] get_diff_end()
[sy:git] set_signs()
[sy:git] Signs updated.
[sy:git] Disable all other VCS.
[sy:hg] job_exit()
[sy:hg] Signs already got updated by git.
```

**Comment by mhinz** [comment]
@Krakonos Oh, of course. -- It should work now!

**Comment by Krakonos** [comment]
Excellect, works fine! Thank you!

**Comment by mhinz** [comment]
Yay, thanks for bringing this up!

**Comment by tzachar** [comment]
Hi,

I am facing the same problem, and the latest version does not solve it.
To elaborate, I have a git repository, in which is nested a mercurial repo (git at /home/tzachar, hg at /home/tzachar/work).
When editing a file in the mercurial repo, signify always uses git to generate the diffs, even though they are empty and hg's are not.

output as requested above:
<pre>
[sy] Register new file: /home/tzachar/work/download_pages.py                                                                            
[sy:git] get_diff_start()                                                                                                                                                     
[sy:git] CMD: ['sh', '-c', 'git diff --no-color --no-ext-diff -U0 -- ''download_pages.py'''] | CWD: /home/tzachar/work/                  
[sy:hg] get_diff_start()                                                                                                                                                      
[sy:hg] CMD: ['sh', '-c', 'hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 -- ''/home/tzachar/work/download_wikipedia_movie_pa
ges.py'''] | CWD: /home/tzachar/work/                                                                                                                    
not found in 'runtimepath': "autoload/UltiSnips.vim"                                                                                                                          
[sy:git] job_exit()                                                                                                                                                           
[sy:git] get_diff_git()                                                                                                                                                       
[sy:git] get_diff_end()                                                                                                                                                       
[sy:git] set_signs()                                                                                                                                                          
[sy:git] Signs updated.                                                                                                                                                       
[sy:hg] job_exit()                                                                                                                                                            
[sy:hg] Signs already got updated by git.                                                                                                                                     
                                                                                                                                                                              
"download_pages.py" 636L, 21906C written                                                                                                           
[sy:git] Updating signs.                                                                                                                                                      
[sy:git] get_diff_start()                                                                                                                                                     
[sy:git] CMD: ['sh', '-c', 'git diff --no-color --no-ext-diff -U0 -- ''download_pages.py'''] | CWD: /home/tzachar/work/                  
[sy:git] job_exit()                                                                                                                                                           
[sy:git] get_diff_git()                                                                                                                                                       
[sy:git] get_diff_end()                                                                                                                                                       
[sy:git] set_signs()                                                                                                                                                          
[sy:git] Signs updated.
</pre>

**Comment by mhinz** [comment]
@tzachar 

The above commit should fix it, please try the latest version.

**Comment by tzachar** [comment]
Thanks, this fixes the issue.
